trad_routes = {
    "homepage": "Homepage",
    "list_player": "List Players",
    "list_players_by_ranking": "List Players by rank",
    "list_players_by_name": "List Players by name",
    "new_player": "New Player",
    "view_player": "View Player",
    "delete_player": "Delete Player",
    "list_tournament": "List Tournaments",
    "new_tournament": "New Tournament",
    "view_tournament": "View Tournament",
    "finish_tournament": "Finish Tournament",
    "select_players": "Select Players",
    "select_all_players": "Select all players",
    "deselect_players": "Deselect Players",
    "list_round": "List Rounds",
    "new_round": "New Round",
    "view_round": "View Round",
    "finish_round": "Finish Round",
    "play_tournament": "Play",
    "save_store": "Save",
    "import_saved_store": "Import save",
    "play_match": "Play match",
    "list_match": "View matchs",
    "quit": "Exit",
}
